version: '3.4'

services:

  netfx-web:
    image: sixeyed/dcsf-netfx:v2
    environment:
      - APPSETTINGS_CONFIG_PATH=C:\netfx-appsettings
      - LOG4NET_CONFIG_PATH=C:\netfx-log4net
    configs:
      - netfx-appsettings
      - netfx-log4net
    networks:
      - netfx
    ports:
    - mode: host
      published: 8082
      target: 80
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

networks:
  netfx:

configs:
  netfx-appsettings:
    external: true
  netfx-log4net:
    external: true