version: '3.3'

services:
  
  message-queue:
    image: nats:linux
    networks:
      - app-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == linux
      
networks:
  app-net: