version: '3.3'

services:

  backplane-db:
    image: dtr.sixeyed.com/dockercon/backplane-db
    secrets:
      - backplane-db.password
    networks:
      - app-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

  web-app:
    image: dtr.sixeyed.com/dockercon/chat-web:v2
    ports:
    - mode: host
      published: 80
      target: 80
    secrets:
      - chat-connection-strings
    networks:
      - app-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

secrets:
  backplane-db.password:
    external: 
      name: chat-db.password
  chat-connection-strings:
    external: 
      name: chat-web.connectionstring

networks:
  app-net: