version: '3.3'

services:

  signup-db:
    image: microsoft/mssql-server-windows-express
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=DockerCon!!!
    networks:
      - app-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

  signup-web:
    image: dtr.sixeyed.com/demo/cloudburst:v2
    environment: 
      - DB_CONNECTION_STRING=Server=signup-db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    networks:
      - app-net
    ports:
    - mode: host
      published: 8088
      target: 80
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

networks:
  app-net: {}