version: '3.3'

services:
  
  signup-db:
    image: signup-db
    networks:
      - app-net

  signup-app:
    image: signup-web:v2
    depends_on:
      - signup-db
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat