version: '3.3'

services:

  netfx-web:
    image: dtrapp-eecus2-vtkj.centralus.cloudapp.azure.com/w2k3-prod/aspnet-webforms:v6
    networks:
      - netfx
    ports:
    - mode: host
      published: 8080
      target: 80
    healthcheck:
      retries: 5
      interval: 10s
    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints:
        - node.platform.os == windows

networks:
  netfx: