version: '3.2'

services:

  db:
    image: microsoft/mssql-server-windows-express
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DockerCon!!!
    ports:
     - mode: host
       published: 1433
       target: 1433
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      - app-net

  web:
    image: dockersamples/signup-web
    environment:
      - DB_CONNECTION_STRING=Server=db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    ports:
     - mode: host
       published: 80
       target: 80
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      - app-net

  save-handler:
    image: dockersamples/signup-save-handler
    environment: 
      - DB_CONNECTION_STRING=Server=db;Database=SignUp;User Id=sa;Password=DockerCon!!!
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      - app-net

  index-handler:
    image: dockersamples/signup-index-handler
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:nanoserver
    ports:
     - mode: host
       published: 5601
       target: 5601
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows
    networks:
      - app-net
      
networks:
  app-net: