version: '3.3'

services:

  sql-db:
    image: sixeyed/bulletin-board-db
    networks:
      - bb-net

  bulletin-board:
    image: sixeyed/bulletin-board
    ports:
      - 8080:8080
    networks:
      - bb-net

networks:
  bb-net: