version: '3.3'

services:

  signup-db:
    image: dtr.sixeyed.com/ipexpo/signup-db
    networks:
      - app-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

  signup-web:
    image: dtr.sixeyed.com/ipexpo/signup-web:v2
    networks:
      - app-net
    ports:
    - mode: host
      published: 80
      target: 8090
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

networks:
  app-net: {}